UPSTREAM: zram: remove request_queue from struct zram
(cherry-pick from commit ee98016010ae036a5b27300d83bd99ef3fd5776e)

`struct zram' contains both `struct gendisk' and `struct request_queue'.
the latter can be deleted, because zram->disk carries ->queue pointer, and
->queue carries zram pointer:

create_device()
	zram->queue->queuedata = zram
	zram->disk->queue = zram->queue
	zram->disk->private_data = zram

so zram->queue is not needed, we can access all necessary data anyway.

Bug: 25951511

Change-Id: If5bcc26c6b1ec69843afdadf745acaa506efc5e6
Signed-off-by: Sergey Senozhatsky <sergey.senozhatsky@gmail.com>
Cc: Minchan Kim <minchan@kernel.org>
Cc: Jerome Marchand <jmarchan@redhat.com>
Cc: Nitin Gupta <ngupta@vflare.org>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

@nathanchance: fix the following error:

drivers/block/zram/zram_drv.c: In function 'create_device':
drivers/block/zram/zram_drv.c:1150:34: error: 'struct zram' has no member named 'queue'
  __set_bit(QUEUE_FLAG_FAST, &zram->queue->queue_flags);
                                  ^~
drivers/block/zram/zram_drv.c: At top level:

Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>